HRIS.Web/Controllers/EmployeeController.cs
using HRIS.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Models;
using Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Resources;
using System.Web;
using System.Web.Mvc;

namespace HRIS.Controllers
{

    public class EmployeeController : BaseController
    {
        // GET: Home
        public ActionResult Index()
        {
            int personId = (int)TempData["PersonIdNo"];
            DateTime effectiveDate = (DateTime)TempData["EffectiveDate"];
            ViewData["PersonId"] = personId;
            ViewData["EffectiveDate"] = effectiveDate;
            KronosEntities context = GetKronosContext();

            ///Employee Header Info
            string empFullName = string.Empty;
            tPERSON person = context.tPERSONS.Where(p => p.PersonIdNo == personId && p.PersonFromEffectDate <= effectiveDate && p.PersonToEffectDate >= effectiveDate).FirstOrDefault();
            if (person != null)
            {
                empFullName = person.LastName.Trim() + ", " + person.FirstName.Trim();
                if (!string.IsNullOrEmpty(person.MiddleName))
                {
                    empFullName += " " + person.MiddleName;
                }

                tEMPLOYMENT_STATUS status = context.tEMPLOYMENT_STATUS.Where(p => p.PersonIdNo == personId && p.EmploymentStatusFromEffectDate <= effectiveDate && p.EmploymentStatusToEffectDate >= effectiveDate).FirstOrDefault();
                if (status != null && !string.IsNullOrEmpty(status.EmpNo))
                {
                    empFullName += " (" + status.EmpNo + ")";
                }
            }
            ViewData["EmpFullName"] = empFullName;

            ///GetGridData
            ViewData["AddressList"] = GetPersonAddresses(personId, context);
            ViewData["PhoneList"] = GetPersonPhones(personId, context);
            ViewData["EmailList"] = GetPersonEmails(personId, context);
            ViewData["PositionList"] = GetPersonPositions(personId, effectiveDate, context);


            ///PayStatus Data
            List<tPERSON_POSITIONS> ppList = context.tPERSON_POSITIONS.Where(p => p.PersonIdNo == personId).ToList();
            List<HRISListObject> posListObj = new List<HRISListObject>();
            List<HRISListObject> primaryPosListObj = new List<HRISListObject>();
            List<HRISListObject> secondaryPosListObj = new List<HRISListObject>();

            primaryPosListObj.AddRange(ppList.Where(p => p.PositionPrimaryInd && p.PositionFromEffectDate <= effectiveDate && p.PositionToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.tPOSITION_IDS != null && p.tPOSITION_IDS.tPOSITION_CODES != null && p.tPOSITION_IDS.tPOSITION_CODES.FirstOrDefault() != null ? p.tPOSITION_IDS.tPOSITION_CODES.FirstOrDefault().PositionCodeDescription : string.Empty, Value = p.PositionIdNo.ToString() }).Distinct().ToList());
            secondaryPosListObj.AddRange(ppList.Where(p => p.PositionPrimaryInd == false && p.PositionFromEffectDate <= effectiveDate && p.PositionToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.tPOSITION_IDS != null && p.tPOSITION_IDS.tPOSITION_CODES != null && p.tPOSITION_IDS.tPOSITION_CODES.FirstOrDefault() != null ? p.tPOSITION_IDS.tPOSITION_CODES.FirstOrDefault().PositionCodeDescription : string.Empty, Value = p.PositionIdNo.ToString() }).Distinct().ToList());

            string personPositionSelectedVal = string.Empty;

            if (primaryPosListObj.Count > 0)
            {
                personPositionSelectedVal = primaryPosListObj[0].Value.ToString();
            }
            else
            {
                if (secondaryPosListObj.Count > 0)
                {
                    personPositionSelectedVal = secondaryPosListObj[0].Value.ToString();
                }
            }

            int pp;
            if (!string.IsNullOrEmpty(personPositionSelectedVal) && int.TryParse(personPositionSelectedVal, out pp))
            {
                ViewData["PayStatusList"] = GetPayStatus(personId, effectiveDate, pp, context);
            }

            ViewData["PayStatusPosition"] = personPositionSelectedVal;
            posListObj.AddRange(primaryPosListObj);
            posListObj.AddRange(secondaryPosListObj);
            ViewData["PayStatusPositionList"] = posListObj.Select(x => new HRISListObject { Description = x.Description, Value = x.Value }).Distinct().ToList(); ;

            TempData["PersonIdNo"] = personId;
            TempData["EffectiveDate"] = effectiveDate;

            return View();
        }

        #region Personal Info

        public ActionResult _PersonalInfo(int personId, DateTime effectiveDate)
        {
            KronosEntities context = GetKronosContext();
            tPERSON personInfo = context.tPERSONS.Where(p => p.PersonIdNo == personId && p.PersonFromEffectDate <= effectiveDate && p.PersonToEffectDate >= effectiveDate).FirstOrDefault();

            if (personInfo == null)
            {
                personInfo = new tPERSON();
            }

            ViewData["MaritalStatusList"] = context.tSY_PERSON_CODES.Where(p => p.PersonCodeType == "MS" || p.PersonCodeType == "NA").Select(p => new HRISListObject { Description = p.PersonCode, Value = p.PersonCodeIdNo.ToString() }).ToList();
            ViewData["GenderList"] = context.tSY_PERSON_CODES.Where(p => p.PersonCodeType == "GN" || p.PersonCodeType == "NA").Select(p => new HRISListObject { Description = p.PersonCode, Value = p.PersonCodeIdNo.ToString() }).ToList();
            ViewData["EthnicOriginList"] = context.tETHNIC_CODES.Where(p => p.EthnicCodeFromEffectDate <= effectiveDate && p.EthnicCodeToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.EthnicCode, Value = p.EthnicCodeIdNo.ToString() }).ToList();
            ViewData["DisabledTypeList"] = context.tMEDICAL_CODES.Where(p => p.MedicalCodeType == "PI" || p.MedicalCodeType == "NA" && p.MedicalCodeFromEffectDate <= effectiveDate && p.MedicalCodeToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.MedicalCode, Value = p.MedicalCodeIdNo.ToString() }).ToList();//vALIDATE
            ViewData["BloodTypeList"] = context.tSY_PERSON_CODES.Where(p => p.PersonCodeType == "BT" || p.PersonCodeType == "NA").Select(p => new HRISListObject { Description = p.PersonCode, Value = p.PersonCodeIdNo.ToString() }).ToList();

            ViewData["BloodFactorList"] = context.tSY_PERSON_CODES.Where(p => p.PersonCodeType == "BF" || p.PersonCodeType == "NA").Select(p => new HRISListObject { Description = p.PersonCode, Value = p.PersonCodeIdNo.ToString() }).ToList();

            ViewData["CitizenshipList"] = context.tTYPE_CODES.Where(p => p.TypeCodeType == "CZ" || p.TypeCodeType == "NA" && p.TypeCodeFromEffectDate <= effectiveDate && p.TypeCodeToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.TypeCode, Value = p.TypeCodeIdNo.ToString() }).ToList(); //vALIDATE
            ViewData["MilitaryServiceList"] = context.tTYPE_CODES.Where(p => p.TypeCodeType == "MS" || p.TypeCodeType == "NA" && p.TypeCodeFromEffectDate <= effectiveDate && p.TypeCodeToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.TypeCode, Value = p.TypeCodeIdNo.ToString() }).ToList();
            ViewData["VisaTypeList"] = context.tVISA_TYPE_CODES.Where(p => p.VisaTypeCodeFromEffectDate <= effectiveDate && p.VisaTypeCodeToEffectDate >= effectiveDate).Select(p => new HRISListObject { Description = p.VisaType, Value = p.VisaType.ToString() }).ToList();

            string userName = string.Empty;
            tSELF_ACCESS access = context.tSELF_ACCESS.Where(s => s.PersonIdNo == personId).FirstOrDefault();
            if (access != null)
            {
                userName = access.UserName;
            }

            ViewData["UserName"] = userName;

            HRISEntities hrisContext = GetHrisContext();

            Module module = hrisContext.Modules.Where(m => m.Name == "Personal Info").FirstOrDefault();

            if (module != null)
            {
                ViewData["PersonalInfoDisabledFields"] = GetDisabledFields(module);
            }

            return View(personInfo);
        }


        public ActionResult SavePersonalInfo(tPERSON person, string neworupdate, DateTime? effectiveDate, string newUserName, string userName)
        {
            person = SaveKronosPersonalInfo(person, neworupdate, effectiveDate, newUserName, userName);
            if (person != null)
            {
                return Json(new
                {
                    status = "success",
                    personIdNo = person.PersonIdNo,
                    personSeqNo = person.PersonSeqNo,
                    timestamp = Convert.ToBase64String(person.Timestamp),
                    effectivefrom = person.PersonFromEffectDate.ToShortDateString(),
                    effectiveto = person.PersonToEffectDate.ToShortDateString()
                });
            }
            else
            {
                return Json(new
                {
                    status = "error"
                });
            }
        }

        public tPERSON SaveKronosPersonalInfo(tPERSON person, string neworupdate, DateTime? effectiveDate, string newUserName, string userName)
        {
            try
            {
                KronosEntities context = GetKronosContext();

                System.Data.Entity.Core.Objects.ObjectParameter idNo = new System.Data.Entity.Core.Objects.ObjectParameter("PersonIdNo", typeof(Int32));
                idNo.Value = person.PersonIdNo;

                System.Data.Entity.Core.Objects.ObjectParameter seqNo = new System.Data.Entity.Core.Objects.ObjectParameter("PersonSeqNo", typeof(Int32));
                seqNo.Value = person.PersonSeqNo;

                double? personUserDefined4 = null;

                if (person.PersonUserDefined4.HasValue)

HRIS.Web/Views/Employee/_Address.cshtml
@using Models;
@using Kendo.Mvc.UI.Html;
@using Resources;
@{ 
    string addressDisabledFields = ViewData["AddressDisabledFields"] != null ? ViewData["AddressDisabledFields"].ToString() : string.Empty;

}
<script>

    function SaveAddress(e)
    {
        $("#Address").kendoValidator
            ({
                onkeyup: false,
                onfocusout: false

            });

        if ($('#Address').data('kendoValidator').validate())
        {
            ShowModal("fullModal");
            var disabled = $("#Address").find(':input:disabled').removeAttr('disabled');
            var serializedData = $("#Address").serialize();
            disabled.attr('disabled', 'disabled');

            $.ajax({
                type: "Post",
                dataType: "json",
                url: '@Url.Action("SaveAddress", "Employee")',
                data: serializedData, // serializes the form's elements.
                success: function (result)
                {
                    HideModal("fullModal");

                    if (result.status == "success")
                    {
                        $('#gridAddress').data("kendoGrid").dataSource.read();

                        $('#PersonAddressSeqNo').val(result.seqNo);
                        $('#AddressTimestamp').val(result.timestamp);

                        NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                        $("#notificationMessage").fadeIn(1000, function ()
                        {
                            $("#notificationMessage").fadeOut(3500);
                        });
                    }
                    else
                    {
                          NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                        $("#notificationMessage").fadeIn(1000, function ()
                        {
                            $("#notificationMessage").fadeOut(3500);
                        });
                    }
                }
            });
        }

        e.preventDefault();
    }


    $(document).ready(function ()
    {
        $("@addressDisabledFields").attr('disabled', 'disabled')

    });


</script>

@model tPERSON_ADDRESSES
<form id="Address">
    <div class="contentinfo">
        <div class="col-md-12">
            <div class="col-md-3">
                @Html.Kendo().Button().Name("btnAddressNew").Content(Resource.New).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("NewAddress"))
                @Html.Kendo().Button().Name("btnAddressSave").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("SaveAddress"))
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <h4>@Resource.Address</h4><br />
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.HiddenFor(m => m.PersonAddressChangeDate)
                        @Html.HiddenFor(m => m.PersonAddressSeqNo)
                        @Html.HiddenFor(m => m.PersonIdNo)
                        @Html.Hidden("AddressTimestamp", Model.Timestamp)
                        @Html.LabelFor(m => m.PersonAddressFromEffectDate, Resource.EffectiveFrom)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().DatePickerFor(m => m.PersonAddressFromEffectDate)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().DatePickerFor(m => m.PersonAddressToEffectDate)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonAddress1, Resource.Address)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().TextBoxFor(m => m.PersonAddress1)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().TextBoxFor(m => m.PersonAddress2)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonAddressCity, Resource.City)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().TextBoxFor(m => m.PersonAddressCity)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonAddressStateProvinceIdNo, Resource.State + ", " + Resource.ZipCode)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().DropDownListFor(m => m.PersonAddressStateProvinceIdNo).BindTo((List<HRIS.Models.HRISListObject>)ViewData["StateList"]).DataTextField("Description").DataValueField("Value").ValuePrimitive(true).OptionLabel(Resource.Select).Filter(FilterType.Contains)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().TextBoxFor(m => m.PersonAddressPostalCode)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonAddressCountryCodeIdNo, Resource.Country)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().DropDownListFor(m => m.PersonAddressCountryCodeIdNo).BindTo((List<HRIS.Models.HRISListObject>)ViewData["CountryList"]).DataTextField("Description").DataValueField("Value").ValuePrimitive(true).OptionLabel(Resource.Select).Filter(FilterType.Contains)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonAddressCountyIdNo, Resource.County)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().DropDownListFor(m => m.PersonAddressCountyIdNo).BindTo((List<HRIS.Models.HRISListObject>)ViewData["CountyList"]).DataTextField("Description").DataValueField("Value").ValuePrimitive(true).OptionLabel(Resource.Select).Filter(FilterType.Contains)
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <h4>@Resource.AddressType</h4><br />
                <div class="col-md-12">
                    <div class="col-md-12">
                        <div class="col-md-3">
                            @Html.LabelFor(m => m.PersonAddressTypeIdNo, Resource.AddressType + "*")
                        </div>
                        <div class="col-md-4">
                            @Html.Kendo().DropDownListFor(m => m.PersonAddressTypeIdNo).BindTo((List<HRIS.Models.HRISListObject>)ViewData["AddressTypeList"]).DataTextField("Description").DataValueField("Value").ValuePrimitive(true).OptionLabel(Resource.Select).Filter(FilterType.Contains).HtmlAttributes(new { required = "required", validationmessage = Resource.AddressType + " " + Resource.IsRequired })
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-3">
                            @Html.LabelFor(m => m.PersonAddressPrimaryInd, Resource.Primary)
                        </div>
                        <div class="col-md-4">
                            @Html.Kendo().CheckBoxFor(m => m.PersonAddressPrimaryInd)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

HRIS.Web/Views/Employee/_Email.cshtml
@using Models;
@using Kendo.Mvc.UI.Html;
@using Resources;
@{
    string emailDisabledFields = ViewData["EmailDisabledFields"] != null ? ViewData["EmailDisabledFields"].ToString() : string.Empty;
}
<script>

    function SaveEmail(e)
    {
        $("#Email").kendoValidator
            ({
                onkeyup: false,
                onfocusout: false
            });

        if ($('#Email').data('kendoValidator').validate())
        {
            ShowModal("fullModal");
            var disabled = $("#Email").find(':input:disabled').removeAttr('disabled');
            var serializedData = $("#Email").serialize();
            disabled.attr('disabled', 'disabled');

            $.ajax({
                type: "Post",
                dataType: "json",
                url: '@Url.Action("SaveEmail", "Employee")',
                data: serializedData, // serializes the form's elements.
                success: function (result)
                {
                    HideModal("fullModal");

                    if (result.status == "success")
                    {
                        $('#EMailSeqNo').val(result.seqNo);
                        $('#EmailTimestamp').val(result.timestamp);

                        $('#gridEmail').data("kendoGrid").dataSource.read();

                        NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                        $("#notificationMessage").fadeIn(1000, function ()
                        {
                            $("#notificationMessage").fadeOut(3500);
                        });
                    }
                    else
                    {
                          NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                        $("#notificationMessage").fadeIn(1000, function ()
                        {
                            $("#notificationMessage").fadeOut(3500);
                        });
                    }
                }
            });
        }

        e.preventDefault();
    }

    $(document).ready(function ()
    {
        $("@emailDisabledFields").attr('disabled', 'disabled');

    });

</script>

@model tEMAIL
<form id="Email">
    <div class="contentinfo">
        <div class="col-md-12">
            <div class="col-md-3">
                @Html.Kendo().Button().Name("btnEmailNew").Content(Resource.New).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("NewEmail"))
                @Html.Kendo().Button().Name("btnEmailSave").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("SaveEmail"))
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-6">
            <h4>@Resource.EmailAddress</h4><br />
            <div class="col-md-12">
                <div class="col-md-3">
                    @Html.HiddenFor(m => m.EMailChangeDate)
                    @Html.HiddenFor(m => m.EMailFromEffectDate)

                    @Html.HiddenFor(m => m.EMailSeqNo)
                    @Html.HiddenFor(m => m.EMailToEffectDate)
                    @Html.HiddenFor(m => m.PersonIdNo)

                    @Html.Hidden("EmailTimestamp", Model.Timestamp)

                    @Html.LabelFor(m => m.EMailAddress, Resource.EmailAddress + "*")
                </div>
                <div class="col-md-4">
                    @Html.Kendo().TextBoxFor(m => m.EMailAddress).HtmlAttributes(new { required = "required" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h4>@Resource.Type</h4><br />
            <div class="col-md-12">
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.EMailPrimaryInd, Resource.Primary)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().CheckBoxFor(m => m.EMailPrimaryInd)
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

HRIS.Web/Views/Employee/_Phone.cshtml
@using Models;
@using Kendo.Mvc.UI.Html;
@using Resources;
@{ 
    string phoneDisabledFields = ViewData["PhoneDisabledFields"] != null ? ViewData["PhoneDisabledFields"].ToString() : string.Empty;
}
<script>
    
    function SavePhone(e)
    {
        $("#Phone").kendoValidator
            ({
                onkeyup: false,
                onfocusout: false
            });

        if ($('#Phone').data('kendoValidator').validate())
        {
            ShowModal("fullModal");
            var disabled = $("#Phone").find(':input:disabled').removeAttr('disabled');
            var serializedData = $("#Phone").serialize();
            disabled.attr('disabled', 'disabled');

            $.ajax({
                type: "Post",
                dataType: "json",
                url: '@Url.Action("SavePhone", "Employee")',
                data: serializedData, // serializes the form's elements.
                success: function (result)
                {
                    HideModal("fullModal");

                    if (result.status == "success")
                    {
                        $('#PersonPhoneSeqNo').val(result.seqNo);
                        $('#PhoneTimestamp').val(result.timestamp);

                        $('#gridPhones').data("kendoGrid").dataSource.read();                        

                        NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                        $("#notificationMessage").fadeIn(1000, function ()
                        {
                            $("#notificationMessage").fadeOut(3500);
                        });
                    }
                    else
                    {
                          NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                        $("#notificationMessage").fadeIn(1000, function ()
                        {
                            $("#notificationMessage").fadeOut(3500);
                        });
                    }
                }
            });
        }

        e.preventDefault();
    }

     $(document).ready(function ()
    {
         $("@phoneDisabledFields").attr('disabled', 'disabled');

    });


</script>

@model tPERSON_PHONES
<form id="Phone">
    <div class="contentinfo">
        <div class="col-md-12">
            <div class="col-md-3">
                 @Html.Kendo().Button().Name("btnPhoneNew").Content(Resource.New).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("NewPhone"))
                @Html.Kendo().Button().Name("btnPhoneSave").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("SavePhone"))
            </div>           
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <h4>@Resource.Phone</h4><br />
                <div class="col-md-12">
                    <div class="col-md-3">                     
                        @Html.HiddenFor(m => m.PersonIdNo)      
                        @Html.HiddenFor(m => m.PersonPhoneChangeDate)      
                        @Html.HiddenFor(m => m.PersonPhoneSeqNo)      
                        @Html.HiddenFor(m => m.PersonPhoneToEffectDate)    
                        @Html.Hidden("PhoneTimestamp", Model.Timestamp)
                        @Html.LabelFor(m => m.PersonPhoneFromEffectDate, Resource.EffectiveFrom)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().DatePickerFor(m => m.PersonPhoneFromEffectDate)
                    </div>                   
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonPhoneNo, Resource.Number+"*")
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().TextBoxFor(m => m.PersonPhoneNo).HtmlAttributes(new { required="required"})
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-3">
                        @Html.LabelFor(m => m.PersonPhoneExt, Resource.Extension)
                    </div>
                    <div class="col-md-4">
                        @Html.Kendo().TextBoxFor(m => m.PersonPhoneExt)
                    </div>
                </div>              
            </div>
            <div class="col-md-6">
                <h4>@Resource.PhoneType</h4><br />
                <div class="col-md-12">
                    <div class="col-md-12">
                        <div class="col-md-3">
                            @Html.LabelFor(m => m.PersonPhoneTypeIdNo, Resource.PhoneType)
                        </div>
                        <div class="col-md-4">
                            @Html.Kendo().DropDownListFor(m => m.PersonPhoneTypeIdNo).BindTo((List<HRIS.Models.HRISListObject>)ViewData["PhoneTypeList"]).DataTextField("Description").DataValueField("Value").ValuePrimitive(true).OptionLabel(Resource.Select).Filter(FilterType.Contains).HtmlAttributes(new { required = "required", validationmessage=Resource.PhoneType + " " + Resource.IsRequired })
                        </div>
                    </div>
                      <div class="col-md-12">
                        <div class="col-md-3">
                            @Html.LabelFor(m => m.PersonPhonePrimaryInd, Resource.Primary)
                        </div>
                        <div class="col-md-4">
                            @Html.Kendo().CheckBoxFor(m => m.PersonPhonePrimaryInd)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>