HRIS.Web/Controllers/EmployeeSearchController.cs
using HRIS.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRIS.Controllers
{
    public class EmployeeSearchController : BaseController
    {
        // GET: EmployeeSearch
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SearchEmployees([DataSourceRequest] DataSourceRequest request, DateTime effectiveDate, string firstName, string lastName, string employeeId, string positionTitle, string supervisorLastName, string status, string socialsecurity)
        {

            var context = GetKronosContext();

            List<EmployeeSearch> list = context.sp_findEmployeesUserAccess(firstName.Trim() + "%", lastName.Trim() + "%", employeeId.Trim() + "%", socialsecurity.Trim() + "%", status == string.Empty ? "%" : status, effectiveDate, false, supervisorLastName.Trim() + "%", positionTitle.Trim() + "%").Select(e => new EmployeeSearch
            {
                EffectiveDate = effectiveDate.ToShortDateString(),
                EmployeeFullName = e.LastName + ", " + e.FirstName + " " + e.MiddleName,
                EmployeeId = e.EmployeeId,
                Organizations = e.Organizations,
                PK1 = e.PK1,
                PK2 = e.PK2,
                PositionTitle = e.PositionTitle,
                SSN = e.SSN,
                Status = e.Status,
                SupervisorFullName = e.SupervisorLastName != string.Empty && e.SupervisorFirstName != string.Empty ? (e.SupervisorLastName + ", " + e.SupervisorFirstName + " " + e.SupervisorMiddleName) : string.Empty,
                IsPrimaryPosition = e.IsPrimaryPosition

            }).ToList();

            foreach (EmployeeSearch child in list)
            {
                child.OrganizationText = String.Join("/", list.Where(c => c.PK1 == child.PK1 && c.PK2 == child.PK2 && child.PositionTitle == c.PositionTitle).OrderBy(c => c.Status).Select(c => c.Organizations));

                if (child.Status != null)
                {
                    string[] st = child.Status.Split('|');
                    if (st.Length > 1)
                    {
                        child.StatusText = st[1];
                    }
                }

                if (child.SupervisorFullName.Trim() == ",")
                {
                    child.SupervisorFullName = string.Empty;
                }

                ///Mark item duplicated if results as employee with more than 1 position
                child.Dupilcated = list.Where(x => x.EmployeeId == child.EmployeeId && x.PK1 == child.PK1 && x.PK2 == child.PK2).Select(x => x.PositionTitle).Distinct().Count() > 1 ? true : false;

            }

            foreach (EmployeeSearch child in list.Where(e => e.Dupilcated).ToList())
            {
                ///Search for the first primary position for fuplicated employee
                string posTit = list.Where(e => e.EmployeeId == child.EmployeeId && e.IsPrimaryPosition == "1").Select(e => e.PositionTitle).FirstOrDefault();

                ///If not [romary position found, set the first position found as primary
                if (string.IsNullOrEmpty(posTit))
                {
                    posTit = list.Where(e => e.EmployeeId == child.EmployeeId).Select(e => e.PositionTitle).FirstOrDefault();
                }

                child.PositionTitle = posTit;
            }

            return Json(list.Select(e => new { e.EffectiveDate, e.EmployeeFullName, e.EmployeeId, e.PK1, e.PK2, e.PositionTitle, e.SSN, e.StatusText, e.SupervisorFullName, e.OrganizationText }).Distinct().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RedirectToEmployee(int personIdNo, DateTime effectiveDate)
        {
            TempData["PersonIdNo"] = personIdNo;
            TempData["EffectiveDate"] = effectiveDate;

            return Json(new { status = "success" });
        }
    }
}

HRIS.Web/Controllers/ProcessedFilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HRIS.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Models;

namespace HRIS.Controllers
{
    public class ProcessedFilesController : BaseController
    {

        // GET: ProcessedFiles
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SearchFiles([DataSourceRequest] DataSourceRequest request, DateTime? fromDate, DateTime? toDate, bool showOnlyError, string employeeId)
        {
            string seedEmpId = "@@##$$%%";
            if(string.IsNullOrEmpty(employeeId))
            {
                employeeId = seedEmpId;
            }
            DateTime seedDate = new DateTime(1900, 1, 1);
            if (fromDate == null)
            {
                fromDate = seedDate;
            }

            if (toDate == null)
            {
                toDate = seedDate;
            }

            var context = GetHrisContext();

            List<ProcessedFilesModel> list = context.ExtractedFiles.Where(f => (f.Date >= fromDate || fromDate == seedDate) && (f.Date <= toDate || toDate == seedDate)&&(f.ExtractedFileModules.Where(s=>s.EmpId == employeeId).Count()>0 || employeeId == seedEmpId)).Select(f =>
            new ProcessedFilesModel
            {
                Date = f.Date,
                FileName = f.Name,
                Id = f.Id,
                Status = f.Status,
                ModuleCount = f.ExtractedFileModules.Count,
                SuccessCount = f.ExtractedFileModules.Where(m => m.Status == "OK").Count(),
                WarningCount = f.ExtractedFileModules.Where(m => m.Status == "warning").Count(),
                ErrorCount = f.ExtractedFileModules.Where(m => m.Status == "error").Count()

            }).ToList();

            if (showOnlyError)
            {
                list = list.Where(l => l.ErrorWarningCount > 0).ToList();
            }

            return Json(list.OrderByDescending(f=>f.Date).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ReadFileModules([DataSourceRequest] DataSourceRequest request, int fileId)
        {
            var context = GetHrisContext();
            List<ProcessedFileModulesModel> list = context.ExtractedFileModules.Where(f => f.ExtractedFileId == fileId).Select(f =>
              new ProcessedFileModulesModel
              {
                  EmployeeId = f.EmpId,
                  Id = f.Id,
                  Info = f.Info,
                  Log = f.Log,
                  ModuleId = f.ModuleId,
                  ModuleName = f.Module.Name,
                  Status = f.Status

              }).ToList();

            foreach (ProcessedFileModulesModel item in list)
            {
                if (!string.IsNullOrEmpty(item.Log))
                {
                    string[] errors = item.Log.Split('#');

                    string log = string.Empty;

                    if (errors.Length > 0)
                    {
                        log += "<ul>";
                        foreach (string mess in errors)
                        {
                            if (mess.Trim() != string.Empty)
                            {
                                log += "<li>" + mess + "</li>";
                            }
                        }

                        log += "</ul>";
                    }

                    item.Log = log;
                }
            }

            return Json(list.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RedirectToEmployee(string empNo, string changes)
        {
            var context = GetKronosContext();

            DateTime effectiveDate = DateTime.Today;

            if(!string.IsNullOrEmpty(changes))
            {
                string[] array = changes.Split('|');
                if(array.Length>3)
                {
                    DateTime.TryParse(array[3], out effectiveDate);
                }
            }

            if(effectiveDate == null)
            {
                effectiveDate = DateTime.Today;
            }

            tEMPLOYMENT_STATUS status = context.tEMPLOYMENT_STATUS.Where(e => e.EmpNo == empNo).FirstOrDefault();


            TempData["PersonIdNo"] = status.PersonIdNo;
            TempData["EffectiveDate"] = effectiveDate;

            return Json(new { status = "success" });
        }
    }


}

HRIS.Web/Views/ProcessedFiles/Index.cshtml
@using Resources
@using HRIS.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>@Resource.ProcessedFiles</h4>
<div class="col-md-12" id="divSearch">
    <div class="col-md-12">
        <div class="col-md-1">

        </div>
        <div class="col-md-1">
            <label> @Resource.From</label>
        </div>
        <div class="col-md-2">
            @Html.Kendo().DatePicker().Name("txtFromDate").Value(DateTime.Today.AddDays(-7))
        </div>
        <div class="col-md-1">
            <label> @Resource.EmployeeId</label>
        </div>
        <div class="col-md-2">
            @Html.Kendo().TextBox().Name("txtEmployeeId")
        </div>
         <div class="col-md-2">
            @Html.Kendo().CheckBox().Name("chbShowOnlyError").Label(@Resource.ShowOnlyFilesError)
        </div>
        <div class="col-md-1">
            @Html.Kendo().Button().Name("btnFind").Content(Resource.Find).Icon("search").Events(ev=>ev.Click("BtnFindClick"))
        </div>
        <div class="col-md-1">

        </div>
    </div>  
    <div class="col-md-12">
          <div class="col-md-1">

        </div>
          <div class="col-md-1">
        <label>    @char.ToUpper(Resource.To[0])@Resource.To.Substring(1) </label>
        </div>
        <div class="col-md-2">
            @Html.Kendo().DatePicker().Name("txtToDate").Value(DateTime.Today.AddDays(1))
        </div>
          <div class="col-md-1">

        </div>
        <div class="col-md-2">

        </div>
       
        
    </div>
</div>
<hr class="searchhr" />
<div class="col-md-12">
     @(Html.Kendo().Grid<ProcessedFilesModel>().Name("gridSearchResults")
        .Columns(c=>
        {
            c.Bound(m => m.Id).Hidden();
            c.Bound(m => m.ErrorCount).Hidden();
            c.Bound(m => m.WarningCount).Hidden();
            c.Bound(m => m.Status).ClientTemplate("<img class='statusimage' style='width:20px' />").Title(Resource.Status).Width(50);
            c.Bound(m => m.Date).Title(Resource.ProcessedDate).Width(150).Format("{0:MM-dd-yyyy}");
            c.Bound(m => m.FileName).Title(Resource.FileName);
            c.Bound(m => m.ModuleCount).Title(Resource.ModuleCount).Width(150);
            c.Bound(m => m.SuccessCount).Title(Resource.SuccessCount).Width(150);
            c.Bound(m => m.ErrorWarningCount).Title(Resource.ErrorWarningCount).Width(150);

        })
        .HtmlAttributes(new{@style="margin-bottom:50px;" })
        .NoRecords(Resource.NoRecordsToDisplay)
        // .Pageable()       
        .Events(ev=>ev.DataBound("SearchResultsDataBound"))
        .ClientDetailTemplateId("ProcessedFileModules")
        .DataSource(d=>
        {
            d.Ajax().Model(m =>
            {
                m.Id(f => f.Id);
            })
            //  .PageSize(10)
            .Read(read=>read.Action("SearchFiles","ProcessedFiles").Data("GetSearchData"));

        }))
      <script id="ProcessedFileModules" type="text/kendo-tmpl">
      @(Html.Kendo().Grid<ProcessedFileModulesModel>().Name("gridFileModule#=Id#")
        .Columns(c=>
        {
            c.Bound(m => m.Id).Hidden();
            c.Bound(m => m.ModuleId).Hidden();
            c.Bound(m => m.Status).ClientTemplate("<img class='modulestatusimage' style='width:15px' />").Title(Resource.Status).Width(50);
            c.Bound(m => m.ModuleName).Title(Resource.ScreenName);
            c.Bound(m => m.Info).Title(Resource.Data);
            c.Bound(m => m.EmployeeId).Title(Resource.EmployeeId);
            c.Bound(m => m.Log).Title(Resource.ErrorLog).Encoded(false);
            c.Command(m =>
            {
                m.Custom("GoToEmployee").Text(Resource.Edit).Click("GoToEmployee").HtmlAttributes(new { @class = "edit", title = Resource.Edit });
            }).Width(100);
        })
        .Events(ev=>ev.DataBound("GridModuleDataBound"))
        .DataSource(d=>
        {
            d.Ajax().Model(m =>
            {
                m.Id(f => f.Id);
            })
            .Read(read=>read.Action("ReadFileModules","ProcessedFiles").Data("GetFileModuleData(#=Id#)"));

        }).ToClientTemplate())
      </script>
</div>


<script>

    
    function GoToEmployee(e)
    {
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"))

        //var url = 'Employee/Index?personId=' + dataItem.PK1 + '&effectiveDate='+dataItem.EffectiveDate
        //window.location = encodeURI(url);     

        $.ajax({
            type: "Post",
            dataType: "json",
            url: '@Url.Action("RedirectToEmployee", "ProcessedFiles")',
            data: { empNo: dataItem.EmployeeId, changes: dataItem.Info}, // serializes the form's elements.
            success: function (result)
            {
                window.location = 'Employee/Index';
            }
        });
    }


    function GetFileModuleData(id)
    {
        return {fileId:id}
    }

    function GridModuleDataBound(e)
    {
        var grid = $("#"+e.sender.element.context.id).data("kendoGrid");
        grid.items().each(function (i, item)
        {
            var dataItem = grid.dataItem(item)
            if (dataItem.Status == 'error')
            {
                $(item).find('.modulestatusimage').attr('src', '/Content/Images/forbidden.png')
            }
            else
            {
                if (dataItem.Status =='warning')
                {
                    $(item).find('.modulestatusimage').attr('src', '/Content/Images/warning.png')
                }
                else
                {
                    $(item).find('.modulestatusimage').attr('src', '/Content/Images/checked.png')
                }
            }
        });
    }

    function SearchResultsDataBound()
    {
        var grid = $("#gridSearchResults").data("kendoGrid");
        grid.items().each(function (i, item)
        {
            var dataItem = grid.dataItem(item)
            if (dataItem.ErrorCount > 0)
            {
                $(item).find('.statusimage').attr('src', '/Content/Images/forbidden.png')
            }
            else
            {
                if (dataItem.WarningCount > 0)
                {
                    $(item).find('.statusimage').attr('src', '/Content/Images/warning.png')
                }
                else
                {
                    $(item).find('.statusimage').attr('src', '/Content/Images/checked.png')
                }
            }
        });
    }

    function EditEmployee(e)
    {
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"))

        //var url = 'Employee/Index?personId=' + dataItem.PK1 + '&effectiveDate='+dataItem.EffectiveDate
        //window.location = encodeURI(url);     

            $.ajax({
                type: "Post",
                dataType: "json",
                url: '@Url.Action("RedirectToEmployee", "EmployeeSearch")',
                data: {personIdNo:dataItem.PK1,effectiveDate:dataItem.EffectiveDate}, // serializes the form's elements.
                success: function (result)
                {
                    window.location = 'Employee/Index';
                }
            });
    }

    function BtnFindClick()
    {
        $('#gridSearchResults').data('kendoGrid').dataSource.read();
    }

    function GetSearchData()
    {
        return {
            fromDate: $('#txtFromDate').val(),
            toDate: $('#txtToDate').val(),
            showOnlyError: $('#chbShowOnlyError').is(":checked"),
            employeeId: $('#txtEmployeeId').val()
        };
    }

</script>