HRIS.Web/Controllers/ConfigurationController.cs
using HRIS.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Models;
using Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Resources;
using System.Web;
using System.Web.Mvc;

namespace HRIS.Controllers
{
    public class ConfigurationController : BaseController
    {
        #region Screen Fields

        public ActionResult ScreenFields()
        {
            var context = GetHrisContext();

            ViewData["ModuleList"] = context.Modules.Select(m => new HRISListObject { Description = m.Name, Value = m.Id.ToString() }).ToList();
            return View();
        }

        public ActionResult _Fields(int moduleId)
        {
            var context = GetHrisContext();
            return View(context.ModuleScreenFields.Where(m => m.ModuleId == moduleId).OrderBy(m => m.ResourceName).ToList());
        }

        public JsonResult SaveScreenFields(List<ModuleScreenField> fields)
        {
            var context = GetHrisContext();

            if (fields != null)
            {
                foreach (ModuleScreenField child in fields)
                {
                    ModuleScreenField field = context.ModuleScreenFields.Where(f => f.Id == child.Id).FirstOrDefault();
                    field.Enabled = child.Enabled;
                }
            }

            context.SaveChanges();

            return Json(new { status = "success" });
        }

        #endregion

        #region Profile Permissions

        public ActionResult ProfilePermissions()
        {
            var context = GetKronosContext();

            ViewData["ProfileList"] = context.LOGONPROFILEs.Select(m => new HRISListObject { Description = m.PROFILEDSC, Value = m.LOGONPROFILEID.ToString() }).OrderBy(p=>p.Description).ToList();
            return View();
        }

        public ActionResult _Sections(int profileId)
        {
            var context = GetHrisContext();

            List<AppSection> secList = context.AppSections.OrderBy(s=>s.Name).ToList();
            List<ProfilePermission> grantedList = context.ProfilePermissions.Where(m => m.LogonProfileId == profileId).ToList();
            List<PermissionModel> list = new List<PermissionModel>();
            int notGrantedId = 0;
            foreach (AppSection child in secList)
            {
                PermissionModel model = new PermissionModel { Name = child.Name, ProfileId = profileId, SectionId = child.Id };               

                ProfilePermission granted = grantedList.Where(p => p.AppSectionId == child.Id && p.LogonProfileId == profileId).FirstOrDefault();
                if (granted != null)
                {
                    model.Id = granted.Id;
                    model.Checked = true;
                }
                else
                {
                    model.Id = --notGrantedId;
                    model.Checked = false;
                }

                list.Add(model);
            }

            return View(list);
        }

        public JsonResult SaveProfilePermissions(List<PermissionModel> permissions)
        {
            var context = GetHrisContext();

            if (permissions != null)
            {
                foreach (PermissionModel child in permissions)
                {
                    if (child.Id > 0 && child.Checked == false)
                    {
                        ProfilePermission perm = context.ProfilePermissions.Where(p => p.Id == child.Id).FirstOrDefault();
                        context.ProfilePermissions.Remove(perm);
                    }
                    else
                    {
                        if(child.Checked)
                        {
                            context.ProfilePermissions.Add(new ProfilePermission { AppSectionId = child.SectionId, LogonProfileId = child.ProfileId });
                        }
                    }
                }
            }

            context.SaveChanges();

            return Json(new { status = "success" });
        }

        #endregion
    }
}

HRIS.Web/Views/Configuration/ProfilePermissions.cshtml
@using Resources
@using Models
@using System.Resources
@{
    ViewBag.Title = Resource.ProfilePermissions;
    Layout = "~/Views/Shared/_Layout.cshtml";

    ResourceManager rm = new ResourceManager(typeof(Resource));
}

<script>
    function GetModuleId()
    {
        return { moduleId: $('#ddlModules').data('kendoDropDownList').value() }
    }

    function SaveProfilePermissions()
    {
        ShowModal("fullModal");

        var permissions = [];
        $("#SectionsForm input.k-checkbox").each(function (e)
        {
            if ($(this).attr("changed") == 'true')
            {
                permissions.push({ Id: $(this).prop("id"), Checked: $(this).is(":checked"), SectionId: $(this).attr("sectionid"), ProfileId: $(this).attr("profileid")  });
            }
        });

        $.ajax({
            type: "Post",
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            url: '@Url.Action("SaveProfilePermissions", "Configuration")',
            data: JSON.stringify({ permissions }), // serializes the form's elements.
            success: function (result)
            {
                HideModal("fullModal");

                if (result.status == "success")
                {
                    NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
                else
                {
                    NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
            }
        });
    }

    function ProfileChanged()
    {
        LoadAppSections()
    }

    function ProfileDataBound()
    {
        LoadAppSections()
    }

    function LoadAppSections()
    {
        $("#divSections").load('@Url.Action("_Sections", "Configuration")' + '?profileId=' + $('#ddlProfiles').data('kendoDropDownList').value(), function ()
        {
            HideModal("fullModal");
        });
    }
  

</script>

<div id="PorfilePermissionsForm">
    <div class="col-md-12">
        <div class="col-md-12">
            <h4>@Resource.ProfilePermissions</h4>
            <div class="col-md-12" >
                @Html.Label(Resource.Profile)
            </div>

            <div class="col-md-2">
                @(Html.Kendo().DropDownList()
                .Name("ddlProfiles")
                .BindTo((List<HRIS.Models.HRISListObject>)ViewData["ProfileList"])
                .DataTextField("Description")
                .DataValueField("Value")
                .ValuePrimitive(true)
                .Filter(FilterType.Contains)
                .Events(ev=>ev.DataBound("ProfileDataBound").Change("ProfileChanged")))   
            </div>
            <div class="col-md-3">
                @Html.Kendo().Button().Name("btnSaveProfilePermissions").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("SaveProfilePermissions")).Icon("update")
            </div>
        </div>
    </div>
     <div class="col-md-12">
     <label>@Resource.SelectPermissionsForProfile</label>
        </div>
    <hr class="searchhr" style="margin-bottom:0" />
    <div id="divSections"></div>
</div>

HRIS.Web/Views/Configuration/ScreenFields.cshtml
@using Resources
@using Models
@using System.Resources
@{
    ViewBag.Title = Resource.ScreenFields;
    Layout = "~/Views/Shared/_Layout.cshtml";

    ResourceManager rm = new ResourceManager(typeof(Resource));
}

<script>
    function GetModuleId()
    {
        return { moduleId: $('#ddlModules').data('kendoDropDownList').value() }
    }

    function SaveScreenFields()
    {
        ShowModal("fullModal");

        var fields = [];
        $("#FieldsForm input.k-checkbox").each(function (e)
        {
            if ($(this).attr("changed") == 'true')
            {
                fields.push({ Id: $(this).prop("id"), Enabled: $(this).is(":checked") });
            }
        });

        $.ajax({
            type: "Post",
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            url: '@Url.Action("SaveScreenFields", "Configuration")',
            data: JSON.stringify({ fields }), // serializes the form's elements.
            success: function (result)
            {
                HideModal("fullModal");

                if (result.status == "success")
                {
                    NotificationMessage('', '@Resource.ChangesSavedSuccessfully', 's');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
                else
                {
                    NotificationMessage('', '@Resource.ErrorSavingEntry', 'd');

                    $("#notificationMessage").fadeIn(1000, function ()
                    {
                        $("#notificationMessage").fadeOut(3500);
                    });
                }
            }
        });
    }

    function ModuleChanged()
    {
        LoadFieldsView()
    }

    function ModulesDataBound()
    {
        LoadFieldsView()
    }

    function LoadFieldsView()
    {
        $("#divScreenFields").load('@Url.Action("_Fields", "Configuration")' + '?moduleId=' + $('#ddlModules').data('kendoDropDownList').value(), function ()
        {
            HideModal("fullModal");
        });
    }

  

</script>

<div id="ScreenFieldsForm">
    <div class="col-md-12">
        <div class="col-md-12">
            <h4>@Resource.ScreenFields</h4>
            <div class="col-md-12" >
                @Html.Label(Resource.Module)
            </div>

            <div class="col-md-2">
                @(Html.Kendo().DropDownList()
                .Name("ddlModules")
                .BindTo((List<HRIS.Models.HRISListObject>)ViewData["ModuleList"])
                .DataTextField("Description")
                .DataValueField("Value")
                .ValuePrimitive(true)
                .Filter(FilterType.Contains)
                .Events(ev=>ev.DataBound("ModulesDataBound").Change("ModuleChanged")))   
            </div>
            <div class="col-md-3">
                @Html.Kendo().Button().Name("btnSaveScreenFields").Content(Resource.Save).HtmlAttributes(new { @style = "margin-bottom:15px; width:100px" }).Events(ev => ev.Click("SaveScreenFields")).Icon("update")
            </div>
        </div>
    </div>
     <div class="col-md-12">
     <label>@Resource.CheckToEnableUncheckToDisable</label>
        </div>
    <hr class="searchhr" style="margin-bottom:0" />
    <div id="divScreenFields"></div>
</div>

HRIS.Web/Views/Configuration/_Fields.cshtml
@using Resources
@using Models
@using System.Resources
@model IEnumerable<ModuleScreenField>
@{
    ResourceManager rm = new ResourceManager(typeof(Resource));
}
<script>

    function CheckBoxChanged(e)
    {
        $(e).attr('changed', 'true');
    }

</script>
<form id="FieldsForm">
    <div class="col-md-12">
        @foreach (var item in Model)
        {
            <div class="col-md-2">@Html.Kendo().CheckBox().Name(item.Id.ToString()).Label(" " + rm.GetString(item.ResourceName) + (item.DisabledByKronos.Value ? " *" : string.Empty)).Checked(item.Enabled.Value).Enable(!item.DisabledByKronos.Value).HtmlAttributes(new { onchange="CheckBoxChanged(this)"})</div>
        }
    </div>
</form>
<hr class="searchhr" />
<div class="col-md-12">
    <label>* &nbsp;@Resource.FieldsDisabledByKronos</label>
</div>

HRIS.Web/Views/Configuration/_Sections.cshtml
@using Resources
@using HRIS.Models
@using System.Resources
@model IEnumerable<PermissionModel>
@{
    ResourceManager rm = new ResourceManager(typeof(Resource));
}
<script>

    function CheckBoxChanged(e)
    {
        $(e).attr('changed', 'true');
    }

</script>
<form id="SectionsForm">
    <div class="col-md-12">
        @foreach (var item in Model)
        {
            <div class="col-md-2">@Html.Kendo().CheckBox().Name(item.Id.ToString()).Label(" " + rm.GetString(item.Name)).Checked(item.Checked).HtmlAttributes(new { onchange="CheckBoxChanged(this)", sectionId = item.SectionId, profileId = item.ProfileId})</div>
        }
    </div>
</form>
<hr class="searchhr" />